@host = localhost:5001
@eventId = 1

### Setup an event
POST https://{{host}}/events/{{eventId}}
Content-Type: application/json

{
    "beers": [
        {
            "id": "ijbock",
            "name": "IJ Bock",
            "brewery": "IJ",
            "style": "Bock",
            "abv": 7.5,
            "type": "Bock",
            "description": "IJ Bock is a dark, strong beer with a full, malty taste and a hint of caramel."
        }
    ],
    "venues": [
        {
            "id": "herberg-jan",
            "name": "Herberg Jan",
            "latitude": 52.123456,
            "longitude": 4.123456,
            "beers": [ "ijbock" ]
        }
    ]
}

### Get event map
GET https://{{host}}/events/{{eventId}}/map

### Get beer selection
GET https://{{host}}/events/{{eventId}}/beers

### Get venue information
GET https://{{host}}/events/{{eventId}}/venues/herberg-jan

### Rate a beer
PUT https://{{host}}/events/{{eventId}}/ratings/amolenk/beers/ijbock
Content-Type: application/json

1

### Check-in
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/amolenk

### Check-out
DELETE https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/amolenk

### Get beer ratings
GET https://{{host}}/events/{{eventId}}/ratings/amolenk











### Get attendance map
GET https://{{host}}/events/{{eventId}}/attendance

### Check-in amolenk
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/amolenk

### Check-in hompus
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/mhompus

### Check-out
DELETE https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/amolenk

### Check-out
DELETE https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/mhompus

### Register a beer
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/beers/ijbock

### Like a beer
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/beers/ijbock/likes?crawlerId=amolenk

### Dislike a beer
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/beers/ijbock/dislikes?crawlerId=amolenk
