@host = localhost:5001
@eventId = bokkentocht-2023

### Register venue
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan

### Check-in amolenk
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/amolenk

### Check-in hompus
POST https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/mhompus

### Check-out
DELETE https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/amolenk

### Check-out
DELETE https://{{host}}/events/{{eventId}}/venues/herberg-jan/crawlers/mhompus
